= Nextcloud Container mit externer Datenbank

== Verzeichnisse erstellen bzw. vorhandene löschen

Achtung: Eventuell vorhanden Volumes vor dem ersten Start löschen und neu erstellen. 

Wurde der Container bereits einmal gestartet, wurden hier auch MySQL-User und Passwort eingetragen. Diese werden durch die Umgebungsvariablen dann nicht mehr verändert. Daher *vor dem ersten* Start am besten beide Volumes löchen.

 sudo rm -r ~/docker/mariadb
 sudo rm -r ~/docker/nextcloud

 mkdir ~/docker/mariadb
 mkdir ~/docker/nextcloud

Wurden beide Container erfolgreich gestartet, und der Zugriff funtkoniert, sollten die Volumes natürlich erhalten bleiben um die Daten persistent zu speichern.

== Netzwerk erstellen

 docker network create db 

== Datenbank Container starten

Zugangsdaten sind nur ein Beispiel und sollten angepasst werden.

 docker run --detach --name nextcloud_db  \
 -v ~/docker/mariadb:/var/lib/mysql \
 --env MARIADB_USER=cloudius \
 --env MARIADB_PASSWORD=cloudiuspw \
 --env MARIADB_DATABASE=nextcloud \
 --env MARIADB_ROOT_PASSWORD=rootpw \
 --network=db \
 --rm mariadb:10.6

== Nextcloud Container starten

Zugangsdaten müssen sich mit denen des Datenbank Containers decken.

 docker run -p 80:80 \
 -v ~/docker/nextcloud:/var/www/html \
 -e NEXTCLOUD_ADMIN_USER=kai \
 -e NEXTCLOUD_ADMIN_PASSWORD=kai \
 -e NEXTCLOUD_TRUSTED_DOMAINS=192.168.100.184 \
 -e MYSQL_DATABASE=nextcloud \
 -e MYSQL_USER=cloudius \
 -e MYSQL_PASSWORD=cloudiuspw \
 -e MYSQL_HOST=nextcloud_db \
 --network=db \
 -d --rm nextcloud


