---

- hosts: all
  become: yes
  vars:
    - user: tux
    - homedir: /home/tux

  tasks:

    - name: Create directory 'documents'
      file:
        path: "{{ homedir }}/documents"
        state: directory

    - name: Create emtpy file inside 'documents' directory
      file:
        path: "{{ homedir }}/documents/emptyfile.txt"
        state: touch

    - name: Install basic packages
      package:
        name:
          - htop
          - sudo 
          - vim
          - ncdu
        state: latest

    - name: Copy over sshd configuration file to disable Password Authentication
      copy:
        src: files/sshd_config
        dest: /etc/ssh/sshd_config
        owner: root
        group: root
        mode: 0644

    - name: Restart SSH Daemon to load new configuration
      systemd_service:
        name: sshd.service
        state: restarted

    - name: Example use of the shell module
      shell: 
        chdir: "{{ homedir }}/documents"
        cmd: 'touch file-from-shell-module'
