version: '2'

volumes:
  nextcloud:
  db:

services:

  nextcloud_db:
    image: mariadb:10.6
    restart: always
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius

  nextcloud_app:
    image: nextcloud
    restart: always
    ports:
      - 8080:80
    links:
      - nextcloud_db
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius
      - MYSQL_HOST=nextcloud_db
