version: '2'

# Angabe der benutzten Volumes
volumes:
  nextcloud:
  db:

# Unter services versteht man die einzelnen Container, die gemeinsam gestartet werden sollen
services:

  # beliebig w채hlbarer Name f체r den Container (das was wir auf der Kommandoszeile mit --name angegeben haben)
  nextcloud_db:
    # das zu verwendende Image
    image: mariadb:10.6
    # ob der Container automatisch neu gestartet werden soll
    restart: always
    # spezielles Kommando f체r Maridb, so aus der Doku 체bernommen
    command: --transaction-isolation=READ-COMMITTED --log-bin=binlog --binlog-format=ROW
    # Angabe aller Volumes
    # verwenden wir hier einen relativen Pfad (beginnend mit ./) werden die Verzeichnisse falls nicht vorhanden von docker erstellt
    volumes:
      - ./db:/var/lib/mysql
    # Angabe aller Umgebungsvariablen (--env, -e)
    environment:
      - MYSQL_ROOT_PASSWORD=rootpw
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius

  nextcloud_app:
    image: nextcloud
    restart: always
    # Port Mapping
    ports:
      - 8080:80
    # Verbindung mit Datenbank Container
    links:
      - nextcloud_db
    volumes:
      - ./nextcloud:/var/www/html
    environment:
      - MYSQL_PASSWORD=cloudiuspw
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=cloudius
      - MYSQL_HOST=nextcloud_db
