= Dokumentation Docker LF10b

== Grundlegendes

=== Image

- Vorlage für beliebig viele Container
- https://hub.docker.com ist eine Platform, auf der Docker Images gehostet werden, Images können von dort mit dem Kommando `docker pull <image>` heruntergeladen werden

=== Container

- wird aus einem Image gebaut
- wird nach Bedarf gebaut, sind _Wegwerfprodukte_: Erledigen eine Aufgabe, werden danach gelöscht und bei Bedarf neu gebaut
- ein Container erledigt in der Regel genau eine Aufgabe (Webserver, Datenbank etc.)
- innerhalb eines Containers läuft also teilweise lediglich ein einzelner Prozess
- wird ein Container gebaut, so erhält er vom Docker Daemon eine ID und einen Namen (beides automatisch generiert)

==== Unterschied zu Virtuellen Maschinen

- sind *keine* Virtuellen Maschinen
- Container laufen dennoch isoliert vom Host-System (ähnlich wie VMs)
- brauchen deutlich weniger Resourcen, da bei Containern nicht die komplette Hardware plus Betriebssystem virtualisiert wird
- Container nutzen den Kernel, Hardware, OS etc. vom Host-System
- Container starten sehr schnell
- es können problemlos dutzende bis hunderte Container auf einem Host laufen

== docker Kommando

- `docker pull <image>`: lädt ein Image (in der Regel von https://hub.docker.com) herunter
- `docker run <image>`: baut einen Container aus dem `<image>`, lädt es bei Bedarf herunter und startet den Container
- `docker start <containername/containerid>`: startet einen bereits gebauten (aber gestoppten) Container
- `docker stop <containername/containerid>`: stoptt einen Container
- `docker ps`: zeigt alle *laufenden* Container an
- `docker ps -a`: zeigt *alle* Container an, auch gestoppte
- `docker ps --all`: zeigt *alle* Container an, auch gestoppte
- `docker exec <container> <kommando>`: führt `<kommando>` im laufenden Container `<container>` aus
- `<kommando>` ist dabei ein beliebiges Kommando, es muss lediglich im Container vorhanden/installiert sein
- `docker exec -it <container> /bin/bash`: startet eine _interaktive_ BASH im laufenden Container `<container>`, wir können uns also im Container bewegen und weitere Kommandos ausführen
- `docker run --name <name> <image>`: Container starten und eigenen Namen `<name>` vergeben

== Ports weiterleiten

- `docker run -p 8080:80 nextcloud`: Startet einen Container aus dem Image `nextcloud` und leitet den Docker-internen Port `80` auf den Port `8080` des Hostsystems weiter
- *Achtung*: Falls der Port auf dem Host bereits von einem anderen Service (regulär oder als anderer Docker Container) genutzt wird, kommt es beim Start eines Containers zu einer Fehlermeldung(`Port already allocated`, `Adress already in use`).

== System aufräumen 

Alle gestoppten Container und zusätzlich nicht benötigte/unvollständige (_Dangling_) Images, Netzwerke etc. Vorhanden intakte Images bleiben erhalten. 

 docker system prune

Es wird nichts gelöscht, was noch benötigt werden kann. Sicher zu benutzen.

=== Container löschen

Nur gestoppte Container können gelöscht werden.

 docker rm <containername/containerid>

=== Iamges löschen

 docker rmi <image:tag>

== Logs

Container produzieren Log-Dateien. Diese sind direkt ersichtlich wenn wir einen Container im Vordergrund starten (also nicht mit der Option `-d`).

Log Dateien können aber auch mit dem folgendem Kommando angezeigt werden:

 docker logs <containername/containerid>

Mit der Option `-f` können die Log Dateien _beobachtet_ werden, es werden also laufend neue Einträge angezeigt:

 docker logs -f <containername/containerid>

== Volumes

Um Daten persistent vorhalten zu können (so dass bestimmte Daten auch nach dem Neu-Erstellen eines Containers noch vorhanden sind) können _Volumes_ verwendet werden.

Z.B. können wir ein beliebiegs Verzeichnis auf dem Host System mit einem beliebigen Verzeichnis innerhalb eines Docker Containers verbinden. Die Verzeichnisse werden dabei _gespiegelt_.

Änderungen in einem Verzeichnis werden direkt auf das andere übertragen.

 docker run -v </pfad/zum/hostverzeichnis>:</pfad/zum/containerverzeichnis> <image>

== Umgebungsvariablen

Um einen Container bereits beim Start/Bau auf eine bestimmte Art zu konfigurieren, können vom Image bereitgestellte Umgebungsvariablen genutzt werden. 

Diese sind unterschiedlich von Container zu Container und können in der Dokumentation des Images (z.B. auf `hub.docker.com`) eingesehen werden.

 docker run -e NAME_ENV_1=wert_env_1 -e NAME_ENV_2=wert_env_2 <image>










